# Generated by Django 4.2 on 2023-04-27 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('metodoPago', models.CharField(blank=True, max_length=200, null=True)),
                ('precioFactura', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precioEnvio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precioTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fechaPago', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('fechaEnvio', models.DateTimeField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('orden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.orden')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('calificacion', models.IntegerField(blank=True, default=0, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DireccionEnvio',
            fields=[
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('codigoPostal', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=200, null=True)),
                ('precioEnvio', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orden')),
            ],
        ),
    ]
